name: CIHaskell
on:
  push:
    branches:
    - main
  # workflow_dispatch:
  #   description: 'Test Tag'
  #   required: false
jobs:
  runner:
    name: ci-test-ref-runner
    uses: trungIsOnGithhub/CIgradingTest/.github/workflows/test.yml@main-feb13-24
